module.exports = {
  JUEGO: {
    RONDAS_POR_BATALLA: 3,
  },
  NIVELES: {
    XP_PARA_SUBIR_NIVEL: 100,
    XP_BASE_POR_VICTORIA: 20,
    XP_MULTIPLICADOR_POR_NIVEL_ENEMIGO: 5,
    VIDA_MAX_POR_NIVEL: 15,
    ATAQUE_POR_NIVEL: 2,
    DEFENSA_POR_NIVEL: 1,
  },
  IA_ENEMIGO: {
    PROBABILIDAD_ATAQUE: 0.60,
    PROBABILIDAD_HABILIDAD: 0.25,
    PROBABILIDAD_OBJETO: 0.15,
  },
};